### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ghost** [mimoguz/tripeaks-gdx#11]
![Screenshot_2021-08-23-18-39-58-209_ogz tripeaks](https://user-images.githubusercontent.com/88626388/130528972-4d56d000-cf3d-40c7-80d3-225de44bff36.jpg)
![Screenshot_2021-08-23-18-40-04-754_ogz tripeaks](https://user-images.githubusercontent.com/88626388/130529073-6ca21442-726a-420e-9654-bc271efeb037.jpg)
![Screenshot_2021-08-23-18-40-21-757_ogz tripeaks](https://user-images.githubusercontent.com/88626388/130529077-97a52b42-90b6-4cf3-ae86-334da6a1961b.jpg)
![Screenshot_2021-08-23-18-40-28-066_ogz tripeaks](https://user-images.githubusercontent.com/88626388/130529082-01a66bf3-5cfc-4fd0-8f87-27ea1d344d09.jpg)
Hello!,
I have found that, when I pick up a card from the top right corner in the third diamond, the card at the top is shown, I don't know if it happens with other diamonds, but the card can even be picked up. (Sorry if my English is bad)

**Comment by mimoguz** [comment]
It was a small mistake in the layout definition. Thanks.

**Comment by Nikoichu** [comment]
![photo_2021-08-26_18-06-30](https://user-images.githubusercontent.com/42444745/130988024-4827c6a1-e2b9-4e41-a2e0-7f26805841bc.jpg)
Got the same bug, don't know if it's supposed to be fixed yet.

**Comment by mimoguz** [comment]
It’s fixed, but F-Droid update cycle is usually about once a week. You can download latest apk from releases page if you want.
