### ISSUE TITLE
Option to choose different card backs

### ISSUE THREAD

**Issue by Nikoichu** [mimoguz/tripeaks-gdx#13]
It would be really nice to be able to customize the card backs (and maybe even the color of the backs? Since they look kinda weird in light mode). So I made some 29 backs for you to use if you want. I made them for dark mode, and the light mode ones are just palette swaps, except the "Praise the Sun" one, which I color-inverted. Feel free to use them, I had a lot of fun making them <3

![Cards](https://user-images.githubusercontent.com/42444745/131001654-fb8b4d2e-c727-43a2-9f99-12d427f20b2f.png)
From left to right, top to bottom:
Default; Swords; Mandala; Honeycomb; Specks; Abstract; Rhombus; Big Mandala; Checkerboard; Dither
Big Swords; Crosses; Smoke; Hourglass; Royal; Hearts; Spades; Clubs; Diamonds; Orb
DNA; Moons; Alchemy; Impossible Triangle; Impossible Square; Simple; Praise the Sun; Industrial; Candles; Eyes

P.S. The PNG is in indexed mode with transparency, although the colors might be a little bit off from yours, due to the color management of my system. If you give me the exact hex codes of the colors I could check that for you.

**Comment by mimoguz** [comment]
It would be nice addition indeed. I will need the patterns by themselves though, without the card images. 

Scene2d.ui, the ui library I use, doesn’t support images in select boxes either. But I want to switch to VisUI anyway, but, in the mid to longish term 🤷‍♂️

**Comment by Nikoichu** [comment]
I see, so without the border. How would you prefer them, as separate files, or as a grid (like it is now)?
Btw, I just have a nice idea, maybe once they're implemented, you could have a "random card back" checkbox that would randomly pick one for each game. Just a thought :3

**Comment by mimoguz** [comment]
> I see, so without the border.

Yes, like the [current back image](https://github.com/mimoguz/tripeaks-gdx/blob/main/resources/images/cards/card_back.png).

> How would you prefer them, as separate files, or as a grid (like it is now)?

Seperate files if possible.

I’m not promising anything though 🙂

**Comment by Nikoichu** [comment]
~~Alrighty, I'll get to it. Light mode versions in a separate zip, I assume?~~ I figured out you use the same texture for both lol
I made 3 more meanwhile, here's a scaled preview version of them all :3
Zip coming soon (tm)
![Cards-export](https://user-images.githubusercontent.com/42444745/131007884-0f5542b6-a31d-4f74-aa12-ea53ab80d473.png)

**Comment by Nikoichu** [comment]
[CardsBacks.zip](https://github.com/mimoguz/tripeaks-gdx/files/7061744/CardsBacks.zip)
Here's the zip, contains 33 backs not including the default. I renamed the dark mode "Praise the Sun" to "PraiseTheMoon" to differentiate the two. If I'm bored I might make a couple more. Let me know if you have any ideas for nice card backs :3

**Comment by Nikoichu** [comment]
![export](https://user-images.githubusercontent.com/42444745/131995941-cba4af5a-fece-43e2-9b75-253898b4ad76.png)
[CardBacks_2.0.zip](https://github.com/mimoguz/tripeaks-gdx/files/7105350/CardBacks_2.0.zip)
[GIF showing light mode cards](https://community.aseprite.org/t/playing-card-backs/10619/4?u=bloodraven0)

Here's a couple more. I kinda went overboard with them, but they're so fun to make! I have a couple more ideas, so I might give you a 3.0 in the future :D
I also updated a few of the older ones, and remade a few as well, so get this zip instead.

I also got a neat idea on unlocking them ingame. The simpler ones (the plain patterns, without a more complex drawing) could be unlocked as a random daily or weekly reward for playing (or winning?) 5 games. The more complex ones could have a thematically appropriate "achievement" for unlocking them - like for example the chess-themed ones could be rewards for winning games on the international chess day - 1 for pawn, 3 for rook, 5 for knight, 7 for bishop, 10 for queen and 15 for king. Others, like the "chains" one could be unlocked by doing a 15-card long chain in one game for example. Or the "praise the sun" back could be rewarded for playing on Dark Souls' release date with light mode on, the "praise the moon" the same - but with dark mode.

I think this would increase player engagement in your game, since people will have something to collect and show off. And the ways for unlocking them could be mysterious - not documented anywhere, so players could share secrets on forums and whatnot (and frown upon data miners that look into the source code to find out how to unlock them lol)

If you want to request a specific card back, I'd love to make it for you, as I said, I've had a lot of fun making these so far. <3

**Comment by Nikoichu** [comment]
![Clubs](https://user-images.githubusercontent.com/42444745/134760771-c8ebdb53-591e-4689-aeea-1f25d87c3e5f.png)
![Diamonds](https://user-images.githubusercontent.com/42444745/134760772-6946efae-59a7-4b06-b3cc-a47c704110bf.png)
![Hearts](https://user-images.githubusercontent.com/42444745/134760773-242eccd2-e203-4910-a29c-e351ca7ca647.png)
![Spades](https://user-images.githubusercontent.com/42444745/134760774-fd6959eb-0311-4f3d-ad14-5bba26e427be.png)
By the way, here's some differently-sized suits if you need them for making other solitaires. Was fooling around with pixel art, thought I'd share. :)

**Comment by mimoguz** [comment]
Would you mind if I replace the current back image with one of your designs?

**Comment by Nikoichu** [comment]
@mimoguz Not at all, although I really like the current design too. Here's hoping you could add multiple of them in the future 😋

**Comment by Nikoichu** [comment]
@mimoguz By the way, in the future you don't have to ask if you could use any of them, I made them specifically for your game after all :)

**Comment by mimoguz** [comment]
Current development branch now has a rudimentary ui for card back design selection.

**Comment by mimoguz** [comment]
This is how it looks:
![screenshot](https://github.com/mimoguz/tripeaks-gdx/blob/oop/.github/images/decor_selection_ui_2024-08-04.png?raw=true)

I need to come up with a ui that can hold more than 4 options, but that's a start.

**Comment by mimoguz** [comment]
Possibly final set:
![Preview](https://github.com/mimoguz/tripeaks-gdx/blob/main/.github/images/decor_preview-2024-08-15.png?raw=true)

I wouldn't mind some input.

**Comment by mimoguz** [comment]
Included in 1.1+. I'm closing the issue for now, but I will re-open it when I start working on a better ui.
