### ISSUE TITLE
How to open the statistics sceen?

### ISSUE THREAD

**Issue by Nikoichu** [mimoguz/tripeaks-gdx#16]
Either I'm dumb or something is going on with the button for the statistics screen.

After updating, the only difference is a small red icon at the top of the "options", which I assume is the statistics screen, but no matter how much tapping, swiping, holding and whatnot I throw at it, it doesn't seem to do anything. I even played some games, since I assumed it didn't open because there was no data to show.

Is this a bug? I'm running Android 10, Poco X3 NFC, Resurrection Remix ROM (degoogled), if any of this matters.

**Comment by mimoguz** [comment]
It's in the in-game menu: [Screenshot](https://1drv.ms/u/s!Ahsda0rPt-lgnvIgLalbzRUcmQPwwA?e=H8sZ3f)

**Comment by Nikoichu** [comment]
Right, I'm blind then, didn't think to check there :D

**Comment by mimoguz** [comment]
🙂
