### ISSUE TITLE
Toki Pona Translation

### ISSUE THREAD

**Issue by ghost** [mimoguz/tripeaks-gdx#17]
Hi, I like doing translations for free software projects, so here you go:

start=o open

fromStack=poki lipu li pana e {0,choice,0#lipu ala|1#lipu wan|1<lipu {0,number,integer}} tawa sina.

usedUndo=sina {0,choice,0#kepeken e nasin pakala la tenpo ala|1#kepeken e nasin pakala la tenpo wan|2#kepeken e nasin pakala la tenpo tu|2<kepeken e nasin pakala la tenpo {0,number,integer}}.

longestChain=tenpo musi ni la pona sina li {0,choice,0#lipu ala|1#lipu wan|1<lipu {0,number,integer}}.

newGame=o open e musi sin

newGameShort=musi sin

exit=o pini

return=o musi

darkTheme=lukin pimeja

showAll=o lukin e lipu ale

won=sina pona!

**Comment by mimoguz** [comment]
Hi. Thanks!

The text you translated is old though. But more importantly, is it even possible to use Toki Pona as the system language on Android or desktop, since the game simply follows that?

**Comment by ghost** [comment]
Oh, I was under the wrong impression that the game had a native language switcher. Sorry. Yeah, if that's not the case, it's not going to work.

The old strings; sorry 'bout that. I could do it over if it's even needed. :/

**Comment by mimoguz** [comment]
No problem. I'm closing the issue, since there would be no way using the translation other than modifying the default resource and building the game using that. Nonetheless, thank you.
