### ISSUE TITLE
Statistics periodically get wiped

### ISSUE THREAD

**Issue by Nikoichu** [mimoguz/tripeaks-gdx#18]
I don't know when or why, but several times now (since statistics were added) when I open the app, play a game, then open the statistics, they only show the game I just played, all previous statistics are gone.

Edit: I just did some testing, and neither force-killing the app, nor restarting the phone seems to wipe the statistics.

**Comment by Nikoichu** [comment]
Some info that could be useful:
I'm using the F-droid version, I'm on a custom Rom (Resurrection Remix) with Android 10, I use microG instead of google services, and google sync and google play are off. 

If there is anything I can do to further diagnose the problem, let me know. Also check the edit to the OP above.

**Comment by mimoguz** [comment]
I reset settings and saves if there is a read error. Probably that.

**Comment by mimoguz** [comment]
The 1.0.1 release includes a small change that might mitigate this issue: the game now retries to load statistics even if it can't load the rest of the saved state.

**Comment by Nikoichu** [comment]
@mimoguz Sadly, it just happened again on v1.0.1

**Comment by mimoguz** [comment]
As I will hopefully release the new version soon, I'm closing the old issues. Please feel free to re-open if the problem resurfaces after v1.1 update.
