### ISSUE TITLE
support custom android icon monochrome theming

### ISSUE THREAD

**Issue by RustoMCSpit** [mimoguz/tripeaks-gdx#23]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by mimoguz** [comment]
Current draft:

![Icon preview](https://github.com/mimoguz/tripeaks-gdx/blob/main/.github/images/adaptive_icon-2024-08-08.png?raw=true)

**Comment by mimoguz** [comment]
Included in current release
