### ISSUE TITLE
Auto dark theme on Android

### ISSUE THREAD

**Issue by jjrpayne** [mimoguz/tripeaks-gdx#26]
An option to auto-select the dark theme based on the user's system settings would be a nice feature.

**Comment by jjrpayne** [comment]
@mimoguz I'd be interested in contributing by implementing this feature. Of course, no worries if you'd rather work on it yourself.

**Comment by mimoguz** [comment]
Hi. I'm not sure if libgdx has an api for querying system theme, but I can add this to my to-do list for my rewrite, that is unfortunately long interrupted due to multiple consecutive health issues. I'll need to redesign the options dialog anyway.

**Comment by jjrpayne** [comment]
I'd be interested in implementing this if I may contribute. I imagine it should be possible to pass the system theme through the Android launcher if an API query doesn't exist.

**Comment by mimoguz** [comment]
A draft implementation on the ```system_theme``` branch.

**Comment by mimoguz** [comment]
Asking for opinions: [issue #27](https://github.com/mimoguz/tripeaks-gdx/issues/27#issuecomment-2312953082)

**Comment by JVariance** [comment]
An improvement would be to select the black theme as dark theme, not as an extra option, so the theme would still be dynamic (light/black).

**Comment by mimoguz** [comment]
I don’t know. I don’t want to remove the ‘regular’ dark theme or overcrowd the options dialog. I’ve actually considered adding a fifth option, like 'system with black' or something, but four options already fill the entire height of the dialog 🙂.

**Comment by mimoguz** [comment]
Included in the 1.2.0 release.

**Comment by mimoguz** [comment]
Included in the 1.2.0 release.
