### ISSUE TITLE
Not fullscreen

### ISSUE THREAD

**Issue by Eggmanplant** [mimoguz/tripeaks-gdx#29]
1.1-beta.3 and newer are not showing fullscreen on Android 15 beta 4. Older versions do.

**Comment by mimoguz** [comment]
Yes, that's deliberate. Title bar should be visible now. Are there any other issues related to this change? Can you post a screen shot if there are?

**Comment by Eggmanplant** [comment]
Can you add an option for fullscreen? The game gets cut off on my Pixel 7a.

**Comment by mimoguz** [comment]
Like this?

![Screen shot](https://github.com/mimoguz/tripeaks-gdx/blob/main/.github/images/pixel7a-2024-08-17.png?raw=true)

So somehow top and bottom parts are just cropped. That wasn't the case on the physical devices I've tested. I think I'll roll back this change on full release until I find a way to do it programmatically with an option.

**Comment by Eggmanplant** [comment]
Yes. Like this.

**Comment by mimoguz** [comment]
I removed the change for now. I'll ask around why the client area isn't resized correctly before re-implementing it. I also replaced the current release with the full screen version.
