### ISSUE TITLE
Restart game

### ISSUE THREAD

**Issue by JVariance** [mimoguz/tripeaks-gdx#30]
It'd be cool, to be able to restart the current game/round by either a distinct button inside the menu or longpressing the undo button.

**Comment by mimoguz** [comment]
I agree 😊. It's already on the [to-do list](https://github.com/mimoguz/tripeaks-gdx/blob/main/todo.md).

**Comment by mimoguz** [comment]
Asking for opinions: [issue #27](https://github.com/mimoguz/tripeaks-gdx/issues/27#issuecomment-2312953082)

**Comment by mimoguz** [comment]
Included in the 1.2.0 release.
