### ISSUE TITLE
Add the ability to rotate the screen clockwise (to the right)

### ISSUE THREAD

**Issue by dantelecan** [mimoguz/tripeaks-gdx#32]
Currently you need to rotate the device counter clockwise (to the left) to play the game. I prefer to rotate the device clockwise (to the right). It would be nice to have in settings an option to rotate this way, or automatically rotate the screen if auto rotate option is enabled in Android settings.

**Comment by mimoguz** [comment]
I think this is more of a bug fix than a new feature. It was a one-word change in the manifest file 🙂.  The fix will be included in the next release.

**Comment by dantelecan** [comment]
Thanks a lot for fixing it! 😀
