### ISSUE TITLE
Free form window support, please.

### ISSUE THREAD

**Issue by derei** [mimoguz/tripeaks-gdx#35]
The app doesn't run in free form window, but it does in split-screen mode.

Please, would it be possible to have the app optimized for free form window?
Thanks.

**Comment by mimoguz** [comment]
I added the required manifest key, so it will be included in the next release. The cropping issue I witnessed when I tried to run the game in non-fullscreen mode before shows up here too, so the window contents will not be vertically centered. I should get back to that  😑.
