### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by izaleu** [mimoguz/tripeaks-gdx#8]
Updated to version 0.46 and the game fails to launch. 0.45 works fine.

Android v11
Pixel 3

**Comment by alexfornuto** [comment]
Same on OnePlus 9, Android 11.

**Comment by elea11** [comment]
same here. the latest build also is only ~350KB in size whereas the previous ones had about 1.2MB.

**Comment by mimoguz** [comment]
> the latest build also is only ~350KB in size whereas the previous ones had about 1.2MB.

350kB? There is something wrong with the f-droid build then. Let me investigate.

**Comment by mimoguz** [comment]
Yep, native libraries were missing in the apk. Turned out a gradle issue, updating the plugin fixed it. Creating a new release for the fix. Thanks!

**Comment by quelbs** [comment]
The F-droid build of 0.46.1 ist still 365kb in size, it still has the same issue.

**Comment by mimoguz** [comment]
Works on my machine!™ I probably messed up something else. That's the downside of not being able to control final build I guess (F-Droid build and package themselves). I will ask F-Droid people to take down 0.46+ if possible, and post apks here until the issue is resolved. 

Thanks.

**Comment by linsui** [comment]
Is this the same issue as https://github.com/yairm210/Unciv/issues/3946?

**Comment by mimoguz** [comment]
> Is this the same issue as [yairm210/Unciv#3946](https://github.com/yairm210/Unciv/issues/3946)?

Seems so. Build plug-in version 4.2.2 with Gradle 7.1.1 worked on my machine, but downgrading to the versions I used in last good release will be safer I guess. Will that be enough?

**Comment by mimoguz** [comment]
Or this (from Unciv)?

     if ("package" in name || "assemble" in name) {
         dependsOn("copyAndroidNatives")
     }

**Comment by linsui** [comment]
If this is the same issue you can reproduce the problem by building from scratch.

**Comment by mimoguz** [comment]
> If this is the same issue you can reproduce the problem by building from scratch.

Hmm. Yes, I can reproduce if I delete the libs folder before build, even with the new versions. So the same issue.

**Comment by mimoguz** [comment]
Changed

    if (packageTask.name.contains("package")) 

to

    if (packageTask.name.contains("package") || packageTask.name.contains("assemble")) 

and now they are in the apk 🙂. I'll do a few more tests with different gradle wrapper/build plugin versions, just to be sure. Please let me know if there is more to this. Thanks.

**Comment by mimoguz** [comment]
Latest release is on the F-Droid and works. Thank you all.

**Comment by mimoguz** [comment]
0.46.2 is now on f-droid. Thank you all.
