### ISSUE TITLE
Card missing on new game start

### ISSUE THREAD

**Issue by izaleu** [mimoguz/tripeaks-gdx#9]
Game version 0.45
Android v11
Pixel 3

Installed game, started new game, very top left card is missing.

![Screenshot_20210705-101628](https://user-images.githubusercontent.com/5201536/124503351-3c28fd80-dd7a-11eb-9a51-2a9dfa11ad41.png)

I was able to beat this game without matching that card, so it is apparently truly "missing" and not a rendering error.

![Screenshot_20210705-101956](https://user-images.githubusercontent.com/5201536/124503522-9aee7700-dd7a-11eb-8845-51ead71dce0c.png)

**Comment by mimoguz** [comment]
Merging with #6

**Comment by izaleu** [comment]
I filed this one separately because the missing card is actually missing, whereas in the other issue the card is just rendered improperly but actually exists.

**Comment by mimoguz** [comment]
New release with re-written core is up. Hopefully these issues are fixed now.
